status_map = {
    3112: "Sikeres megrendelés",
    2896: "Elfogadott ajánlat",
    2895: "Elfogadásra vár",
    2894: "Vázlat",
    3014: "Elutasítva",
    2897: "Sztornózva",
    3112: "Sikeres megrendelés",
    3023: "Felmérésre vár",
    3083: "Utalásra vár",
    3084: "Elszámolásra vár",
    2927: "Új érdeklődő",
    2933: "Felmérés szervezés",
    2894: "Vázlat (nincs kiadva)",
    3082: "Felmérés előkészítés",
    2929: "Sikertelen felmérés",
    3086: "Sikeres felmérés",
}

todo_map = {
    "23": {
        "": "",
        203: "Felmérés szervezés",
        225: "Felmérés",
        202: "Visszahívás",
        241: "Rendszerhiba E3",
        242: "Kapcsolat",
        227: "Új jelentkező - BOSS!",
        237: "Pénzügy díjbekérő",
        239: "Felmérés - BOSS!",
        224: "Pénzügyi elszámolás",
        240: "Rendszerhiba E2",
        238: "Pénzügy számlázás",
        246: "Pénzügy visszatérítés",
        245: "Rendszerhiba E5",
        244: "Rendszerhiba E4",
        249: "Rendszerhiba E6",
        235: "Rendszerhiba E1",
    },
    "33": {
        268: "Rendszergarancia",
        263: "Rendszerbővítés",
        269: "Karbantartás",
        267: "Szerviz",
        264: "Műszaki egyeztetés",
        257: "Ügyfélkapu szervezés",
        258: "Ügyfélkapu kiszállás",
        261: "Új garancia",
        272: "Ügyfélkapu kapcsolat",
        259: "Ügyfélkapu díjbekérő",
        260: "Ügyfélkapu számlázás",
        265: "Ügyfélkapu visszafizetés",
        266: "Új karbantartás",
        277: "Új szerviz",
        281: "Új bővítés",
        285: "Rendszerhiba E1",
        282: "Rendszerhiba E2",
        286: "Rendszerhiba E3",
        287: "Rendszerhiba E4",
        283: "Új jelentkező - BOSS!",
        284: "Felmérés - BOSS!",
        288: "Rendszerhiba E5",
    },
}

garancia_type_map = {
    "Teljes garancia": "Teljes",
    "Feltételes garancia": "Részleges",
    "Eszköz garancia": "Eszköz",
    "Nem adunk garanciát a rendszerre": "Nincs",
}
